### <능력단위 평가 : 빅데이터 수집시스템 개발 2026. 07. 03. 금>

# 한국마사회_농어촌형 승마시설정보 데이터 수집 파이프라인 - API 방식

- 공공 API로 한국마사회_농어촌형 승마시설정보 데이터를 수집하고, 변환/검증 한 뒤 PostgreSQL과 CSV로 저장하기
- API : 한국마사회_농어촌형 승마시설정보

## 전체 파이프라인 흐름

1. 공공데이터포털에서 원하는  API 활용 신청
2. 환경설정 : API 키 준비(.env), 기본 설정 준비
3. 수집 : JSON 구조 확인, 전체 페이지 수집
4. 판다스의 데이터프레임 만들기
5. 파생컬럼(파생변수) 추가
7. 데이터 검증(생략 가능)
8. DB 저장 : 먼저 pgAdmin에서 DB  생성(horsedb)-> 테이블 저장(horse_info)
9. CSV 저장 : horse_info.csv 인코딩 설정(utf-8-sig)

In [2]:
# 라이브러리 불러오기

import math
import os
import time
from datetime import date
import pandas as pd
import requests
from dotenv import load_dotenv
from sqlalchemy import create_engine, text

In [3]:
# API 키 불러오기

load_dotenv()
API_KEY = os.getenv('HORSE_API_KEY')

if API_KEY: 
    print(f'API키 로드 완료: {API_KEY[:6]}...{API_KEY[-4:]}')
else:
    print('env 파일에 API키를 설정하세요.')

API키 로드 완료: 6fa3bb...9029

In [ ]:
# API 연결 테스트 

response = requests.get('https://apis.data.go.kr/B551015/API132',params={'serviceKey': API_KEY, 'srwrd': '경기' })

In [ ]:
BASE_URL = 'https://apis.data.go.kr/B551015/API132/ffvCefInfo'
response =requests.get(BASE_URL, params={'serviceKey': API_KEY, 'pageNo':1, 'numOfRows':10, 'srwrd': '경기', '_type':'json'})
response.json()

In [17]:
data = response.json()
data['response']['body']['items']['item'][0]['pobAdr']

'경기도 양주시 은현면 용암로265번길 139-46'

In [26]:
# 환경 설정

BASE_URL = 'https://apis.data.go.kr/B551015/API132/ffvCefInfo'
ROWS_PER_PAGE = 1000
REQUEST_TIMEOUT = 60

In [27]:
# 저장 경로

BASE_DIR = os.getcwd()  # 현재 위치
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
OUTPUT_PATH = os.path.join(OUTPUT_DIR, 'horse_info.csv')

In [28]:
#PostgreSQL 설정

DB_URL = 'postgresql://postgres:1234@localhost:5432/horsedb'
TABLE_NAME = 'horse_info'

print(f'csv 저장경로: {OUTPUT_PATH}')

csv 저장경로: c:\Users\Administrator\bigdata2026\fastapi\05_horse_api_pipeline\output\horse_info.csv

In [29]:
data['response']['body']['totalCount']

28

In [30]:
total_count = data['response']['body']['totalCount']
total_pages = math.ceil(total_count / ROWS_PER_PAGE)

print(f'전체 건수 : {total_count:,}개')
print(f'페이지당 건수 : {ROWS_PER_PAGE:,}개')
print(f'총 페이지 건수 : {total_pages:,}페이지')

전체 건수 : 28개
페이지당 건수 : 1,000개
총 페이지 건수 : 1페이지

In [31]:
all_items = []

for page_no in range(1, total_pages + 1):
    params={
        "serviceKey": API_KEY, 
        "pageNo": page_no, 
        "numOfRows": ROWS_PER_PAGE,  
        "_type": 'json'
    }

    response = requests.get(BASE_URL, params=params, timeout=REQUEST_TIMEOUT)
    response.raise_for_status()

    page_body = response.json()['response']['body']

    if not page_body.get('items'):
        print(f'{page_no}/{total_pages} 페이지: 페이지 없음')
        continue 
    page_items = page_body['items'].get('item', [])

    if isinstance(page_items, dict):
        page_items=[page_items]

    all_items.extend(page_items) 
    
    print(f'{page_no}/{total_pages} 페이지 수집 완료 -> 누적 {len(all_items):,}건')
    
    time.sleep(0.2)
    
print(f'전체 수집 완료 : {len(all_items):,}건')

1/1 페이지 수집 완료 -> 누적 105건
전체 수집 완료 : 105건

In [32]:
# Frame 만들기

df_raw = pd.DataFrame(all_items)

print(f'데이터프레임의 크기: {df_raw.shape}')
print(f'컬럼 목록: {df_raw.columns.tolist()}')

데이터프레임의 크기: (105, 8)
컬럼 목록: ['cefType', 'dayof', 'hrcosIntrWritTxt', 'oprEndTm', 'oprStartTm', 'pobAdr', 'pobNm', 'repsTelNo']

In [33]:
df_raw.head()

,cefType,dayof,hrcosIntrWritTxt,oprEndTm,oprStartTm,pobAdr,pobNm,repsTelNo
0,"그린승마존, 유소년승마시설, 승용조련시설",월,안녕하세요! 금강홀스랜드 승마장입니다. 즐겁고 안전한 기승을 위해 최선을 다하는...,18:00,08:00,경기도 용인시 처인구 원삼면 원양로246번길 153,금강홀스랜드,031-334-9872
1,"그린승마존, 유소년승마시설",월,-,19:00,08:00,경기도 광주시 도척면 방도길 137-32,광주승마클럽,031-766-0763
2,그린승마존,월,-,18:00,09:00,전라남도 나주시 남평읍 지석로 807-91,골드레이크 승마장,010-7226-2432
3,"그린승마존, 유소년승마시설, 승용조련시설",월,2002년 아시안 게임 장애물 부분 개인 은메달을 획득한 전 국가대표 출신이 운영하...,18:00,08:00,울산광역시 울주군 삼남면 자수정로 70,JK호스트레이닝공원,052-264-0500
4,"그린승마존, 유소년승마시설, 승용조련시설",-,-,00:00,00:00,경상북도 구미시 고아읍 원대로20길 18,구미승마장,054-453-0150

In [38]:
# 컬럼명 정의

COLUMN_RENAME = {
    'cefType':'시설유형', 
    'dayof': '휴관일', 
    'hrcosIntrWritTxt': '승마장소개', 
    'oprEndTm': 'CLOSE', 
    'oprStartTm': 'OPEN', 
    'pobAdr': '주소',
    'pobNm': '승마장이름',
    'repsTelNo': '전화번호'
}

df = df_raw.rename(columns=COLUMN_RENAME)
df

,시설유형,휴관일,승마장소개,CLOSE,OPEN,주소,승마장이름,전화번호
0,"그린승마존, 유소년승마시설, 승용조련시설",월,안녕하세요! 금강홀스랜드 승마장입니다. 즐겁고 안전한 기승을 위해 최선을 다하는...,18:00,08:00,경기도 용인시 처인구 원삼면 원양로246번길 153,금강홀스랜드,031-334-9872
1,"그린승마존, 유소년승마시설",월,-,19:00,08:00,경기도 광주시 도척면 방도길 137-32,광주승마클럽,031-766-0763
2,그린승마존,월,-,18:00,09:00,전라남도 나주시 남평읍 지석로 807-91,골드레이크 승마장,010-7226-2432
3,"그린승마존, 유소년승마시설, 승용조련시설",월,2002년 아시안 게임 장애물 부분 개인 은메달을 획득한 전 국가대표 출신이 운영하...,18:00,08:00,울산광역시 울주군 삼남면 자수정로 70,JK호스트레이닝공원,052-264-0500
4,"그린승마존, 유소년승마시설, 승용조련시설",-,-,00:00,00:00,경상북도 구미시 고아읍 원대로20길 18,구미승마장,054-453-0150
...,...,...,...,...,...,...,...,...
100,"그린승마존, 승용조련시설",월,-,18:00,09:00,제주특별자치도 제주시 애월읍 산록서로 81,더홀스승마센터,010-2732-3666
101,"그린승마존, 유소년승마시설",월,-,00:00,00:00,경상남도 창원시 의창구 북면 백월로295번길 26-46,동백승마클럽,010-7517-1186
102,그린승마존,"월, 화",-,17:00,09:00,충청남도 예산군 대술면 마전삼베실길 56-32,말길 홀스브릿지,010-2031-5548
103,"그린승마존, 유소년승마시설",월,충북 보은군에 위차한 보은 승마 아카데미는 말과 사람이 함께 어우러지는 힐링 복합 ...,19:00,09:30,충청북도 보은군 탄부면 월송로 364,보은승마아카데미,010-4264-1164
104,그린승마존,월,-,00:00,00:00,전북특별자치도 익산시 삼기면 용연길 271,익산승마장,010-2979-2833

In [ ]:
# 필요없는 승마장소개 컬럼 제거

df = df.drop('승마장소개', axis=1) 
df

,시설유형,휴관일,CLOSE,OPEN,주소,승마장이름,전화번호
0,"그린승마존, 유소년승마시설, 승용조련시설",월,18:00,08:00,경기도 용인시 처인구 원삼면 원양로246번길 153,금강홀스랜드,031-334-9872
1,"그린승마존, 유소년승마시설",월,19:00,08:00,경기도 광주시 도척면 방도길 137-32,광주승마클럽,031-766-0763
2,그린승마존,월,18:00,09:00,전라남도 나주시 남평읍 지석로 807-91,골드레이크 승마장,010-7226-2432
3,"그린승마존, 유소년승마시설, 승용조련시설",월,18:00,08:00,울산광역시 울주군 삼남면 자수정로 70,JK호스트레이닝공원,052-264-0500
4,"그린승마존, 유소년승마시설, 승용조련시설",-,00:00,00:00,경상북도 구미시 고아읍 원대로20길 18,구미승마장,054-453-0150
...,...,...,...,...,...,...,...
100,"그린승마존, 승용조련시설",월,18:00,09:00,제주특별자치도 제주시 애월읍 산록서로 81,더홀스승마센터,010-2732-3666
101,"그린승마존, 유소년승마시설",월,00:00,00:00,경상남도 창원시 의창구 북면 백월로295번길 26-46,동백승마클럽,010-7517-1186
102,그린승마존,"월, 화",17:00,09:00,충청남도 예산군 대술면 마전삼베실길 56-32,말길 홀스브릿지,010-2031-5548
103,"그린승마존, 유소년승마시설",월,19:00,09:30,충청북도 보은군 탄부면 월송로 364,보은승마아카데미,010-4264-1164
104,그린승마존,월,00:00,00:00,전북특별자치도 익산시 삼기면 용연길 271,익산승마장,010-2979-2833

In [ ]:
# '도'와 '시'를 기준으로 지역 추가

si_do_list = [ 
    "서울특별시", "부산광역시", "대구광역시", "인천광역시", "광주광역시", "대전광역시", "울산광역시",
    "세종특별자치시", "경기도", "강원특별자치도", "충청북도", "충청남도", "전북특별자치도", "전라남도", "경상북도", "경상남도",  "제주특별자치도" ]

# 함수 정의
def get_si_do(stop_name):
    """주소에 포함된 시, 도를 찾아 반환하는 함수"""
    stop_name = str(stop_name)

    for si_do in si_do_list:
        if si_do in stop_name:     # gu값이 stop_name에 포함되었니?
            return si_do
    return '기타'
if '주소' in df.columns:
    df['지역']=df['주소'].apply(get_si_do)

df

,시설유형,휴관일,CLOSE,OPEN,주소,승마장이름,전화번호,지역
0,"그린승마존, 유소년승마시설, 승용조련시설",월,18:00,08:00,경기도 용인시 처인구 원삼면 원양로246번길 153,금강홀스랜드,031-334-9872,경기도
1,"그린승마존, 유소년승마시설",월,19:00,08:00,경기도 광주시 도척면 방도길 137-32,광주승마클럽,031-766-0763,경기도
2,그린승마존,월,18:00,09:00,전라남도 나주시 남평읍 지석로 807-91,골드레이크 승마장,010-7226-2432,전라남도
3,"그린승마존, 유소년승마시설, 승용조련시설",월,18:00,08:00,울산광역시 울주군 삼남면 자수정로 70,JK호스트레이닝공원,052-264-0500,울산광역시
4,"그린승마존, 유소년승마시설, 승용조련시설",-,00:00,00:00,경상북도 구미시 고아읍 원대로20길 18,구미승마장,054-453-0150,경상북도
...,...,...,...,...,...,...,...,...
100,"그린승마존, 승용조련시설",월,18:00,09:00,제주특별자치도 제주시 애월읍 산록서로 81,더홀스승마센터,010-2732-3666,제주특별자치도
101,"그린승마존, 유소년승마시설",월,00:00,00:00,경상남도 창원시 의창구 북면 백월로295번길 26-46,동백승마클럽,010-7517-1186,경상남도
102,그린승마존,"월, 화",17:00,09:00,충청남도 예산군 대술면 마전삼베실길 56-32,말길 홀스브릿지,010-2031-5548,충청남도
103,"그린승마존, 유소년승마시설",월,19:00,09:30,충청북도 보은군 탄부면 월송로 364,보은승마아카데미,010-4264-1164,충청북도
104,그린승마존,월,00:00,00:00,전북특별자치도 익산시 삼기면 용연길 271,익산승마장,010-2979-2833,전북특별자치도

In [44]:
# PostgreSQL 저장

def save_to_postgresql(df, db_url, table_name):
  
    df_save =df.copy()
    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)
    
    engine = create_engine(db_url)

    with engine.connect() as conn:
        version= conn.execute(text('SELECT version();')).fetchone()[0]
        print("PostgreSQL 연결 성공~")
        print(version[:80] + '.....')

    df_save.to_sql(
        name= table_name,
        con= engine,
        if_exists= 'replace',
        index= False,
        chunksize= 1000,
        method= 'multi'
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]

    print(f'저장 완료: {saved_count:,}행')
    print(f'DB: busapidb / table: {table_name}')

In [45]:
save_to_postgresql(df, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공~
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit.....
저장 완료: 105행
DB: busapidb / table: horse_info

In [46]:
# CSV 저장

os.makedirs(OUTPUT_DIR, exist_ok=True)

df.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('csv 저장 완료!')

csv 저장 완료!