# 대구 지하철 승하차 데이터 수집 파이프라인 - csv 파일 방식

## 전체 파이프라인 흐름
0. 환경설정 : 라이브러리 불러오기, 경로, DB URL 설정
1. 수집 : CSV 파일 읽기(인코딩 --> 윈도우 cp949(최신 utf-8))
2. 변환 : 파일에 따라
3. 파생컬럼(파생변수) : ex) 시작시 / 날짜 / 요일코드 / 주말여부
4. 검증 : 유효성 검증, 리포터 출력
5. DB 저장 : Postgresql -> subwaydb생성 
6. CSV 저장 : outpou 폴더 안에 CSV파일로 저장(utf-8-sig)

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

# --- 경로 설정 ---
# ipynb파일은 getcwd()함수를 이용해서 파일 위치나 폴도 위치를 가져온다.
BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\01_subway_pipeline'

In [ ]:
# 입력파일 경로 설정
DATA_PATH = os.path.join(BASE_DIR, 'input', 'subway_raw.csv')  # 베이스디렉토리, input 폴더 안에 subway_raw.csv파일 불러와서 DATA_PATH에 저장
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\01_subway_pipeline\\input\\subway_raw.csv'

In [ ]:
# 출력파일 경로 설정
OUTPUT_PATH = os.path.join(BASE_DIR, 'output', 'subway_long.csv')
OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\01_subway_pipeline\\output\\subway_long.csv'

In [ ]:
# ---Postgresql 데이터베이스 연결 ---
DB_URL = 'postgresql://postgres:1234@localhost:5432/subwaydb'

## 공공데이터의 시간대별 데이터

### Wide : 
 역명 | 승하 | 09시~06시 | 06시~07시 |.....| 23시~24시 | 일계|
 설화명곡 | 승차 | 22 | 37 | .....| 47 | 2867 |

### Long : 
역명|승하|시간대컬럼|인원수|
설화명곡|승차|05시~06시|22|
설화명곡|승차|06시~07시|37|

- Long 형태가 DB 저장, 시각화, 분석 모두에 적합하다.
- Long 형태로 변환하기 위해서 pd.melt()를 사용한다.

In [4]:
# --- 요일 코드 매핑 ---
# dt.weekday 반환값 : 월 == 0, 화 == 1, ...
WEEKDAY_NAMES = {0:'월', 1:'화', 2:'수', 3:'목', 4:'금', 5:'토', 6:'일'}

In [7]:
# --- 데이터 수집 ---
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')
df_raw.head()

,월,일,역번호,역명,승하차,05시-06시,06시-07시,07시-08시,08시-09시,09시-10시,...,15시-16시,16시-17시,17시-18시,18시-19시,19시-20시,20시-21시,21시-22시,22시-23시,23시-24시,일계
0,1,1,1150,설화명곡,승차,46,51,72,114,125,...,200,164,135,112,109,49,38,27,11,2194
1,1,1,1150,설화명곡,하차,4,84,39,70,86,...,150,182,189,186,147,113,98,124,77,2108
2,1,1,1160,화원,승차,27,39,47,91,138,...,218,204,167,85,69,51,38,32,7,2338
3,1,1,1160,화원,하차,3,83,63,64,149,...,207,215,156,124,91,107,90,79,57,2385
4,1,1,1170,대곡,승차,40,67,62,118,154,...,165,162,157,103,85,65,47,37,6,2205

In [8]:
# --- 행과 열의 갯수 ---
df_raw.shape

(28388, 25)

In [9]:
# --- 열이름 전체 확인 ---
df_raw.columns

Index(['월', '일', '역번호', '역명', '승하차', '05시-06시', '06시-07시', '07시-08시',
       '08시-09시', '09시-10시', '10시-11시', '11시-12시', '12시-13시', '13시-14시',
       '14시-15시', '15시-16시', '16시-17시', '17시-18시', '18시-19시', '19시-20시',
       '20시-21시', '21시-22시', '22시-23시', '23시-24시', '일계'],
      dtype='str')

In [11]:
for i, col in enumerate(df_raw.columns):
    print(f'[{i}] {col}')

[0] 월
[1] 일
[2] 역번호
[3] 역명
[4] 승하차
[5] 05시-06시
[6] 06시-07시
[7] 07시-08시
[8] 08시-09시
[9] 09시-10시
[10] 10시-11시
[11] 11시-12시
[12] 12시-13시
[13] 13시-14시
[14] 14시-15시
[15] 15시-16시
[16] 16시-17시
[17] 17시-18시
[18] 18시-19시
[19] 19시-20시
[20] 20시-21시
[21] 21시-22시
[22] 22시-23시
[23] 23시-24시
[24] 일계

In [12]:
# --- 데이터 타입 확인 ---
df_raw.dtypes

월          int64
일          int64
역번호        int64
역명           str
승하차          str
05시-06시    int64
06시-07시    int64
07시-08시    int64
08시-09시    int64
09시-10시    int64
10시-11시    int64
11시-12시    int64
12시-13시    int64
13시-14시    int64
14시-15시    int64
15시-16시    int64
16시-17시    int64
17시-18시    int64
18시-19시    int64
19시-20시    int64
20시-21시    int64
21시-22시    int64
22시-23시    int64
23시-24시    int64
일계         int64
dtype: object

In [15]:
# --- 결측치 확인 ---
null_counts = df_raw.isnull().sum()
if null_counts.any():
    print('결측치 발견!~')
    print(null_counts[null_counts > 0])
else:
    print('결측치 없음!')

결측치 없음!

In [20]:
id_cols = ['월','일','역번호','역명','승하차']
time_cols = [c for c in df_raw.columns if '시-' in c]
print(f'시간대별 컬럼 수 : {len(time_cols)}개')
print(f'시간대별 컬럼 목록 : {time_cols}')

시간대별 컬럼 수 : 19개
시간대별 컬럼 목록 : ['05시-06시', '06시-07시', '07시-08시', '08시-09시', '09시-10시', '10시-11시', '11시-12시', '12시-13시', '13시-14시', '14시-15시', '15시-16시', '16시-17시', '17시-18시', '18시-19시', '19시-20시', '20시-21시', '21시-22시', '22시-23시', '23시-24시']

## pd.melt() --> wide를 long으로 변환
df.melt(데이터프레임, id_vars = 유지할 열, value_vars = 행으로 만들 열, var_name = 새열의 이름, value_name = 값을 담을 새 열의 이름)

In [25]:
df_long = pd.melt(df_raw, id_vars=id_cols, value_vars=time_cols, var_name='시간대컬럼', value_name='인원수')
df_long = df_long.reset_index(drop=True)
df_long.shape

(539372, 7)

## 파생컬럼(파생변수) 추가

### 정규표현식으로 숫자 추출
r'^(\d+)시' 
- r : 정규표현식에서 문자를 표현
- ^ : 문자열 맨 앞
- (\d+) : 숫자 하나 이상

ex) 05시 == 5 (int로 형 변환)

In [29]:
# --- 시작시 컬럼 추가 ---
# 05~06시 --> 앞의 숫자만 추출 --> 정수로 변환

df_long['시작시'] = df_long['시간대컬럼'].str.extract(r'^(\d+)시' )
df_long['시작시']

0         05
1         05
2         05
3         05
4         05
          ..
539367    23
539368    23
539369    23
539370    23
539371    23
Name: 시작시, Length: 539372, dtype: str

In [30]:
df_long.head()

   월  일   역번호    역명 승하차    시간대컬럼  인원수 시작시
0  1  1  1150  설화명곡  승차  05시-06시   46  05
1  1  1  1150  설화명곡  하차  05시-06시    4  05
2  1  1  1160    화원  승차  05시-06시   27  05
3  1  1  1160    화원  하차  05시-06시    3  05
4  1  1  1170    대곡  승차  05시-06시   40  05

In [32]:
# ---  날짜 컬럼 추가 ___
YEAR = 2026

df_long['일']

0          1
1          1
2          1
3          1
4          1
          ..
539367    31
539368    31
539369    31
539370    31
539371    31
Name: 일, Length: 539372, dtype: int64

### pd.to_datetime(dict)
- 연/월/일 딕셔너리를 한 번에 datetime으로 변환

In [33]:
df_series = pd.to_datetime(dict(year=YEAR, month= df_long['월'], day =df_long['일']))
df_series

0        2026-01-01
1        2026-01-01
2        2026-01-01
3        2026-01-01
4        2026-01-01
            ...
539367   2026-05-31
539368   2026-05-31
539369   2026-05-31
539370   2026-05-31
539371   2026-05-31
Length: 539372, dtype: datetime64[us]

In [36]:
df_long['날짜']=df_series.dt.date
df_long

        월   일   역번호    역명 승하차    시간대컬럼  인원수 시작시          날짜
0       1   1  1150  설화명곡  승차  05시-06시   46  05  2026-01-01
1       1   1  1150  설화명곡  하차  05시-06시    4  05  2026-01-01
2       1   1  1160    화원  승차  05시-06시   27  05  2026-01-01
3       1   1  1160    화원  하차  05시-06시    3  05  2026-01-01
4       1   1  1170    대곡  승차  05시-06시   40  05  2026-01-01
...    ..  ..   ...   ...  ..      ...  ...  ..         ...
539367  5  31  3390    지산  하차  23시-24시   38  23  2026-05-31
539368  5  31  3400    범물  승차  23시-24시   15  23  2026-05-31
539369  5  31  3400    범물  하차  23시-24시   47  23  2026-05-31
539370  5  31  3410    용지  승차  23시-24시    5  23  2026-05-31
539371  5  31  3410    용지  하차  23시-24시   24  23  2026-05-31

[539372 rows x 9 columns]

In [ ]:
# ---  요리 코드 컬럼 추가 ---
df_series.dt.weekday # 월==0, 화==1,....

0         3
1         3
2         3
3         3
4         3
         ..
539367    6
539368    6
539369    6
539370    6
539371    6
Length: 539372, dtype: int32

In [37]:
# .map(WEEKDAY_NAMES) --> 숫자로 된 요일 번호가 한글 요일로 나온다.

df_long['요일'] = df_series.dt.weekday.map(WEEKDAY_NAMES)
df_long

        월   일   역번호    역명 승하차    시간대컬럼  인원수 시작시          날짜 요일
0       1   1  1150  설화명곡  승차  05시-06시   46  05  2026-01-01  목
1       1   1  1150  설화명곡  하차  05시-06시    4  05  2026-01-01  목
2       1   1  1160    화원  승차  05시-06시   27  05  2026-01-01  목
3       1   1  1160    화원  하차  05시-06시    3  05  2026-01-01  목
4       1   1  1170    대곡  승차  05시-06시   40  05  2026-01-01  목
...    ..  ..   ...   ...  ..      ...  ...  ..         ... ..
539367  5  31  3390    지산  하차  23시-24시   38  23  2026-05-31  일
539368  5  31  3400    범물  승차  23시-24시   15  23  2026-05-31  일
539369  5  31  3400    범물  하차  23시-24시   47  23  2026-05-31  일
539370  5  31  3410    용지  승차  23시-24시    5  23  2026-05-31  일
539371  5  31  3410    용지  하차  23시-24시   24  23  2026-05-31  일

[539372 rows x 10 columns]

In [38]:
# --- 주말 여부 컬럼 추가 ---
# 토=5, 일=6 이면 True
df_long['주말여부'] = df_series.dt.weekday >= 5
df_long

        월   일   역번호    역명 승하차    시간대컬럼  인원수 시작시          날짜 요일   주말여부
0       1   1  1150  설화명곡  승차  05시-06시   46  05  2026-01-01  목  False
1       1   1  1150  설화명곡  하차  05시-06시    4  05  2026-01-01  목  False
2       1   1  1160    화원  승차  05시-06시   27  05  2026-01-01  목  False
3       1   1  1160    화원  하차  05시-06시    3  05  2026-01-01  목  False
4       1   1  1170    대곡  승차  05시-06시   40  05  2026-01-01  목  False
...    ..  ..   ...   ...  ..      ...  ...  ..         ... ..    ...
539367  5  31  3390    지산  하차  23시-24시   38  23  2026-05-31  일   True
539368  5  31  3400    범물  승차  23시-24시   15  23  2026-05-31  일   True
539369  5  31  3400    범물  하차  23시-24시   47  23  2026-05-31  일   True
539370  5  31  3410    용지  승차  23시-24시    5  23  2026-05-31  일   True
539371  5  31  3410    용지  하차  23시-24시   24  23  2026-05-31  일   True

[539372 rows x 11 columns]

In [39]:
# --- 최종 컬럼의 목록 ---
df_long.columns

Index(['월', '일', '역번호', '역명', '승하차', '시간대컬럼', '인원수', '시작시', '날짜', '요일',
       '주말여부'],
      dtype='str')

In [ ]:
# .tolist() : 리스트로 형 변환
df_long.columns.tolist()

['월', '일', '역번호', '역명', '승하차', '시간대컬럼', '인원수', '시작시', '날짜', '요일', '주말여부']

In [41]:
# --- 최종 데이터 타입 ---
df_long.dtypes

월         int64
일         int64
역번호       int64
역명          str
승하차         str
시간대컬럼       str
인원수       int64
시작시         str
날짜       object
요일          str
주말여부       bool
dtype: object

In [ ]:
# ---- 월 일  컬럼 삭제 ----
df_long = df_long.drop('월', axis=1) 
df_long = df_long.drop('일', axis=1) 
df_long

         역번호    역명 승하차    시간대컬럼  인원수 시작시          날짜 요일   주말여부
0       1150  설화명곡  승차  05시-06시   46  05  2026-01-01  목  False
1       1150  설화명곡  하차  05시-06시    4  05  2026-01-01  목  False
2       1160    화원  승차  05시-06시   27  05  2026-01-01  목  False
3       1160    화원  하차  05시-06시    3  05  2026-01-01  목  False
4       1170    대곡  승차  05시-06시   40  05  2026-01-01  목  False
...      ...   ...  ..      ...  ...  ..         ... ..    ...
539367  3390    지산  하차  23시-24시   38  23  2026-05-31  일   True
539368  3400    범물  승차  23시-24시   15  23  2026-05-31  일   True
539369  3400    범물  하차  23시-24시   47  23  2026-05-31  일   True
539370  3410    용지  승차  23시-24시    5  23  2026-05-31  일   True
539371  3410    용지  하차  23시-24시   24  23  2026-05-31  일   True

[539372 rows x 9 columns]