# 실습문제 : 공영주차장 CSV 컬럼 추출 & Postgresql 저장

### 데이터 안내

- 데이터명: 대구광역시 북구_공영주차장 운영 현황 및 현장 정보

- 인코딩: `cp949` 

👉 https://www.data.go.kr/data/15096499/fileData.do

### 요구사항
1. CSV 파일을 pandas로 읽어 원본 데이터를 확인하시오.
    - `encoding="cp949"`로 읽으시오.
    - `df.shape`, `df.columns.tolist()`, `df.head()`로 구조를 확인하시오.

In [1]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

BASE_DIR = os.getcwd()
BASE_DIR

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking_lot'

In [2]:
# 입력파일 경로
DATA_PATH = os.path.join(BASE_DIR, 'input', 'parking_lot_raw.csv') 
DATA_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking_lot\\input\\parking_lot_raw.csv'

In [3]:
# 출력파일 경로
OUTPUT_PATH = os.path.join(BASE_DIR, 'output', 'parking_lot.csv')
OUTPUT_PATH

'c:\\Users\\Administrator\\bigdata2026\\fastapi\\02_parking_lot\\output\\parking_lot.csv'

In [4]:
# Postgresql 데이터베이스 연결
DB_URL = 'postgresql://postgres:1234@localhost:5432/parkingdb'

In [5]:
# 데이터 수집
df_raw = pd.read_csv(DATA_PATH, encoding='cp949')

In [6]:
df_raw.shape

(229, 27)

In [7]:
df_raw.columns.tolist()

['순번',
 '주차장관리번호',
 '주차장명',
 '주차장 유형',
 '소재지지번주소',
 '주차구획수',
 '급지구분',
 '부제시행구분',
 '운영요일',
 '평일운영시작시각',
 '평일운영종료시각',
 '토요일운영시작시각',
 '토요일운영종료시각',
 '공휴일운영시작시각',
 '공유일운영종료시각',
 '요금정보',
 '주차기본시간',
 '주차기본요금',
 '추가단위시간',
 '추가단위요금',
 '1일주차권요금적용시간',
 '1일주차권적용시간',
 '월정기요금',
 '결제방법',
 '관리기관명',
 '경도',
 '위도']

In [8]:
df_raw.head()

,순번,주차장관리번호,주차장명,주차장 유형,소재지지번주소,주차구획수,급지구분,부제시행구분,운영요일,평일운영시작시각,...,주차기본요금,추가단위시간,추가단위요금,1일주차권요금적용시간,1일주차권적용시간,월정기요금,결제방법,관리기관명,경도,위도
0,1,154-1-000001,3공단로25길인근,노상,대구광역시 북구 노원동3가 191-1,6,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.897770,128.565410
1,2,154-1-000002,3공단로인근,노상,대구광역시 북구 노원동3가 14,329,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시청,35.899471,128.569853
2,3,154-1-000003,검단동로인근,노상,대구광역시 북구 검단동 745-2,29,3,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.913949,128.625135
3,4,154-1-000004,경대로17길인근,노상,대구광역시 북구 복현동 573,78,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892740,128.612720
4,5,154-1-000005,경대로23길인근,노상,대구광역시 북구 복현동 606-34,5,2,미시행,평일+토요일+공휴일,00:00:00,...,0,0,0,0,0,0,0,대구광역시 북구청,35.892602,128.616021

### 요구사항
2. 아래 **3개 컬럼만** 선택해서 새로운 DataFrame을 만드시오.
    - `주차장명`
    - `소재지지번주소`
    - `주차구획수`

In [9]:
df_new = df_raw[['주차장명', '소재지지번주소', '주차구획수']]
df_new.head()

        주차장명               소재지지번주소  주차구획수
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6
1     3공단로인근     대구광역시 북구 노원동3가 14    329
2     검단동로인근    대구광역시 북구 검단동 745-2     29
3   경대로17길인근      대구광역시 북구 복현동 573     78
4   경대로23길인근   대구광역시 북구 복현동 606-34      5

### 요구사항
3. 선택한 데이터를 PostgreSQL `parkingdb`에 `parking_lot`이라는 이름의 테이블로 저장하시오.
    - `parkingdb`는 미리 pgAdmin에서 만들어 두어야 합니다.

In [29]:
def save_to_postgresql(df, db_url, table_name):
    df_save = df.copy()
    for col in df_save.columns:
        if pd.api.types.is_string_dtype(df_save[col]):
            df_save[col] = df_save[col].astype(str)    

    engine = create_engine(db_url)

    with engine.connect() as conn:
        version = conn.execute(text('SELECT version();')).fetchone()[0]
        print('PostgreSQL 연결 성공!')
        print(version[:80]+'....')

    df_save.to_sql(
        name=table_name,
        con=engine,
        if_exists='replace',
        index=False,
        chunksize=1000,
        method='multi'
    )

    with engine.connect() as conn:
        saved_count = conn.execute(text(f'SELECT COUNT(*) FROM {table_name};')).fetchone()[0]

    print(f'저장 완료!{saved_count:,}행')
    print(f'DB : subwaydb / table: {table_name}')

In [30]:
TABLE_NAME ='parking_lot'

In [31]:
save_to_postgresql(df_new, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit....
저장 완료!229행
DB : subwaydb / table: parking_lot

### 요구사항
4. 저장 후 pgAdmin에서 테이블과 데이터를 직접 확인하시오.

df_new.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('CSV 저장 완료!')
print(f'경로: {OUTPUT_PATH}')
print(f'크기: {len(df_new):,}행 X {len(df_new.columns)}열')

In [32]:
df_new.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('CSV 저장 완료!')
print(f'경로: {OUTPUT_PATH}')
print(f'크기: {len(df_new):,}행 X {len(df_new.columns)}열')

CSV 저장 완료!
경로: c:\Users\Administrator\bigdata2026\fastapi\02_parking_lot\output\parking_lot.csv
크기: 229행 X 6열

## 심화 문제

### A — 규모 구분 컬럼 추가

`주차구획수`를 기준으로 주차장 규모를 구분하는 컬럼 `규모구분`을 추가하시오.

<aside>
💡

> 20면 미만    → "소형"
20~50면      → "중형"
50면 초과    → "대형"
> 
</aside>

In [ ]:
def parking_size(size):
    if size < 20:
        return "소형"
    elif size <= 50:
        return "중형"
    else:
        return "대형"

df_new['규모구분'] = df_new['주차구획수'].apply(parking_size)
df_new.head()

        주차장명               소재지지번주소  주차구획수 규모구분
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형
1     3공단로인근     대구광역시 북구 노원동3가 14    329   대형
2     검단동로인근    대구광역시 북구 검단동 745-2     29   중형
3   경대로17길인근      대구광역시 북구 복현동 573     78   대형
4   경대로23길인근   대구광역시 북구 복현동 606-34      5   소형

## 심화 문제

### B — 무료/유료 구분

원본의 `요금정보` 컬럼을 함께 가져온 뒤, `fee_type` 컬럼을 추가하시오.

```
요금정보가 무료이면 → 무료
그 외 → 유료
```

In [21]:
def fee_type(info):
    if info == '무료':
        return '무료'
    else:
        return '유료'

df_new['fee_type'] = df_raw['요금정보'].apply(fee_type)
df_new.head()

        주차장명               소재지지번주소  주차구획수 규모구분 fee_type
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형       무료
1     3공단로인근     대구광역시 북구 노원동3가 14    329   대형       무료
2     검단동로인근    대구광역시 북구 검단동 745-2     29   중형       무료
3   경대로17길인근      대구광역시 북구 복현동 573     78   대형       무료
4   경대로23길인근   대구광역시 북구 복현동 606-34      5   소형       무료

## 심화 문제

### C — 동(洞) 이름 추출 컬럼 추가

`소재지지번주소`에서 동 이름만 뽑아 `동이름` 컬럼을 추가하시오.

<aside>
💡

"대구광역시 북구 노원동3가 191-1" → "노원동3가"
"대구광역시 북구 검단동 745-2"    → "검단동"

</aside>

> 힌트: 주소가 항상 `시 / 구 / 동 / 번지` 4개 조각으로 띄어쓰기 되어 있습니다.
> 
> 
> `str.split()`으로 나눈 뒤 3번째 조각(인덱스 2번)만 가져오면 됩니다.
>

In [25]:
df_new['동이름'] = df_raw['소재지지번주소'].str.split().str[2]
df_new.head()

        주차장명               소재지지번주소  주차구획수 규모구분 fee_type    동이름
0  3공단로25길인근  대구광역시 북구 노원동3가 191-1      6   소형       무료  노원동3가
1     3공단로인근     대구광역시 북구 노원동3가 14    329   대형       무료  노원동3가
2     검단동로인근    대구광역시 북구 검단동 745-2     29   중형       무료    검단동
3   경대로17길인근      대구광역시 북구 복현동 573     78   대형       무료    복현동
4   경대로23길인근   대구광역시 북구 복현동 606-34      5   소형       무료    복현동

In [27]:
save_to_postgresql(df_new, DB_URL, TABLE_NAME)

PostgreSQL 연결 성공!
PostgreSQL 17.10 on x86_64-windows, compiled by msvc-19.44.35227, 64-bit....
저장 완료!229행
DB : subwaydb / table: parking_lot

In [26]:
df_new.to_csv(OUTPUT_PATH, encoding='utf-8-sig', index=False)

print('CSV 저장 완료!')
print(f'경로: {OUTPUT_PATH}')
print(f'크기: {len(df_new):,}행 X {len(df_new.columns)}열')

CSV 저장 완료!
경로: c:\Users\Administrator\bigdata2026\fastapi\02_parking_lot\output\parking_lot.csv
크기: 229행 X 6열